import Head from "next/head";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export async function getServerSideProps() {
  const features = await prisma.Feature.findMany();
  return {
    props: {
      initialFeatures: features,
    },
  };
}

export default function Home({ initialFeatures }) {
  const [features, setFeatures] = useState(initialFeatures);
  useEffect(() => {
    console.log(features);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className={styles.main}>
        {features && features.map((item) => item.creator)}
      </main>
    </div>
  );
}
